#
# Airflow Service
#

version: '3.1'
services:
    
    #
    # Nginx acts as a proxy to centralize any web services listed on here.
    #
    nginx:
        network_mode: "host"
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/airflow
            - ./logs:/var/log/nginx/airflow/
        expose:
            - 80
            - 443
    #
    # Redis Server - Serves as a queueing system for celery (a distributed task manager)
    #
    redis:
        image: redis
        network_mode: "host"
        expose:
            - 6379

    #
    # Postgres - User management and configuration storage, data persited to local volume.
    #

    postgres:
        image: postgres:10
        network_mode: "host"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        expose:
            - 5432
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    #
    # Airflow server
    #

    airflow:
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: "host"
        expose:
            - 8080
            - 5555
            - 8793
        restart: unless-stopped
        depends_on:
            - postgres
            - redis
            - nginx
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_HOST=localhost
            - REDIS_HOST=localhost
        env_file:
            - ../config/airflow.env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 5
