---

name: Cause airflow production to refresh DAGs

on:
  pull_request:
    branches:
      - production
    types:
      - closed

jobs:
  deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_API_TOKEN }}
          WEBHOOK_KEY: "op://Discovery Day/airflow.fyi webhook key/password"

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.AIRFLOW_WEBHOOK_URL}}
          webhook_secret: ${{ env.WEBHOOK_KEY }}
          data: '{ "webhook_key": "${{ env.WEBHOOK_KEY }}" }'
