---

name: Cause airflow production to refresh DAGs

on:
  pull_request:
    branches:
      - production
    types:
      - closed

jobs:
  deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Configure 1Password Connect
        uses: 1password/load-secrets-action/configure@v1
        with:
          # Persist the 1Password Connect configuration for next steps.
          connect-host: ${{ secrets.OP_CONNECT }}
          connect-token: ${{ secrets.OP_API_TOKEN}}

      - name: Load web hook access token from 1Password
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          WEBHOOK_KEY: "op://${{ secrets.OP_VAULT_ID  }}/Airflow Webhook/password"

      - name: Load web hook address from 1Password
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          WEBHOOK_ADDRESS: "op://${{ secrets.OP_VAULT_ID }}/Airflow Webhook/smee/address"
      
      - name: Invoke authenticated deployment web hook
        run: 'curl -X POST -H "X-Webhook-Key: ${{ env.WEBHOOK_KEY }}" ${{ env.WEBHOOK_ADDRESS }}'
